DROP DATABASE IF EXISTS EMPLOYEE_DB;

USE employee_db;

CREATE TABLE department(
id INT UNSIGNED NOT NULL
AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL);

CREATE TABLE role(
id INT UNSIGNED NOT NULL
AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL(8,2) NOT NULL,
department_id INT UNSIGNED NOT NULL,
FOREIGN KEY (department_id)
REFERENCES department(id));

CREATE TABLE employee(
id INT UNSIGNED NOT NULL
AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT UNSIGNED NOT NULL,
FOREIGN KEY (role_id)
REFERENCES role(id));